#version 460

#include "scene.glsl"

// layout (std140, set = 0, binding = 0) uniform SceneData - scene.glsl

layout (set = 1, binding = 0) uniform sampler2D filteredAO;
layout (set = 1, binding = 1) uniform sampler2D historyOutputAO;
layout (set = 1, binding = 2) uniform sampler2D depthBuffer;
layout (set = 1, binding = 2) uniform sampler2D velocityBuffer;
layout (r8, set = 1, binding = 2) uniform image2D outputAO;

void main() {

}
