name: Windows CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
  VULKAN_SDK_VERSION: 1.3.275.0  # Specify the exact version you want to use

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Visual Studio shell
        uses: microsoft/setup-msbuild@v1.1

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: ${{env.VULKAN_SDK_VERSION}}
          cache: true

      - name: Add Vulkan SDK to Path
        shell: powershell
        run: |
          echo "VULKAN_SDK=$env:VULKAN_SDK" | Out-File -FilePath $env:GITHUB_ENV -Append
          echo "$env:VULKAN_SDK\Lib" | Out-File -FilePath $env:GITHUB_PATH -Append
          echo "$env:VULKAN_SDK\Bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}