name: Windows CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository (without LFS)
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Cache LFS objects
        uses: actions/cache@v4
        with:
          path: .git/lfs
          key: lfs-${{ runner.os }}-${{ hashFiles('.lfs-assets-id') }}
          restore-keys: |
            lfs-${{ runner.os }}-

      - name: Pull LFS objects
        run: git lfs pull

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Set up Visual Studio shell
        uses: microsoft/setup-msbuild@v1.1

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.1.1
        with:
          version: latest
          cache: true
          cache-key: vulkan-sdk-${{ runner.os }}

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}