name: Windows CMake Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cached LFS checkout
        uses: nschloe/action-cached-lfs-checkout@v1

      - name: Update submodules
        run: |
          git submodule update --init --recursive

      - name: Set up Visual Studio shell
        uses: microsoft/setup-msbuild@v1.1

      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@c2aa128094d42ba02959a660f03e0a4e012192f9
        with:
          version: latest
          cache: true

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}